routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\LyricController;
use App\Http\Controllers\PdfController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/login', function () {
    return view('login');
})->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('attempt.login');

Route::middleware('auth')
    ->group(function () {
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

        Route::prefix('lyrics')
            ->as('lyrics.')
            ->group(function () {
                Route::get('', [LyricController::class, 'index'])->name('index');
                Route::get('create', [LyricController::class, 'create'])->name('create');
                Route::post('create', [LyricController::class, 'store'])->name('store');
                Route::get('{id}', [LyricController::class, 'show'])->name('show');
                Route::get('{id}/edit', [LyricController::class, 'edit'])->name('edit');
                Route::put('{id}', [LyricController::class, 'update'])->name('update');
                Route::delete('{id}', [LyricController::class, 'destroy'])->name('destroy');
            });

        Route::post('{id}/pdf-generate', [PdfController::class, 'generateExport'])->name('pdf.generate');

        Route::get('/download', function () {
            return view('download');
        })->name('download');
    });

app/Models/Lyric.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Lyric extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'user_id',
        'part_1',
        'part_2',
        'part_3',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @param $value
     * @return string
     */
    public function getCreatedAtAttribute($value): string
    {
        $createdAt = Carbon::parse($value);
        return $createdAt->format('d M Y');
    }

    /**
     * @param $value
     * @return string
     */
    public function getUpdatedAtAttribute($value): string
    {
        $createdAt = Carbon::parse($value);
        return $createdAt->format('d M Y');
    }

}

app/Http/Controllers/LyricController.php
<?php

namespace App\Http\Controllers;

use App\Services\LyricService;
use App\Http\Requests\StoreLyricRequest;
use App\Http\Requests\UpdateLyricRequest;
use Illuminate\Http\RedirectResponse;

class LyricController extends Controller
{
    /**
     * LyricController constructor
     */
    public function __construct(private LyricService $lyricService)
    {
        $this->lyricService = $lyricService;
    }

    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $lyrics = $this->lyricService->getLyrics();

        return view('lyrics.index', compact('lyrics'));
    }

    /**
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('lyrics.create');
    }

    /**
     * @param StoreLyricRequest $request
     * @return RedirectResponses
     */
    public function store(StoreLyricRequest $request): RedirectResponse
    {
        try {
            $lyric = $this->lyricService->createLyric($request);

            return redirect()
                ->route('lyrics.index')
                ->with('success', 'Lyric successfully added.');
        } catch (Exception $e) {
            return redirect()->back()->withInput();
        }
    }

    /**
     * @param  int $id
     * @return \Illuminate\View\View|\Illuminate\Http\RedirectResponse
     */
    public function show($id)
    {
        $lyric = $this->lyricService->getLyric($id);

        if ($lyric) {
            return view('lyrics.pdf.template', compact('lyric'));
        } else {
            return redirect()
                ->route('lyrics.index')
                ->with('error', 'Lyric not found.');
        }
    }

    /**
     * @param  int $id
     * @return \Illuminate\View\View|\Illuminate\Http\RedirectResponse
     */
    public function edit($id)
    {
        $lyric = $this->lyricService->getLyric($id);

        if ($lyric) {
            return view('lyrics.edit', compact('lyric'));
        } else {
            return redirect()
                ->route('lyrics.index')
                ->with('error', 'Lyric not found.');
        }
    }

    /**
     * @param int $id
     * @param UpdateLyricRequest $request
     * @return RedirectResponse
     */
    public function update($id, UpdateLyricRequest $request): RedirectResponse
    {
        try {
            $result = $this->lyricService->updateLyric($id, $request);

            if($result) {
                return redirect()
                    ->route('lyrics.index')
                    ->with('success', 'Lyric successfully updated.');
            }

            return redirect()->back()->with('error', 'Something went wrong, please try again.');
        } catch (Exception $e) {
            return redirect()->back()->withInput();
        }
    }

    /**
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy($id): RedirectResponse
    {
        try {
            $result = $this->lyricService->deleteLyric($id);

            if ($result) {
                return redirect()
                    ->route('lyrics.index')
                    ->with('success', 'Lyric successfully deleted.');
            }

            return redirect()
                ->route('lyrics.index')
                ->with('error', 'Lyric not found.');
        } catch (Exception $e) {
            return redirect()->back()->with('error', 'Something went wrong, please try again.');
        }
    }
}

resources/views/lyrics/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid mt-5">
        <div>
            <div>
                <h1 class="mb-5">Add Lyric</h1>
            </div>
        </div>
        <form
            method="post"
            action="{{ route('lyrics.store') }}"
            class="container-fluid border-start border-primary p-3"
        >
            @csrf
            <div class="row">
                <div class="col-12">
                    <div class="mb-3">
                        <label for="title"><b>Title</b></label>
                        <input
                            class="form-control"
                            id="title"
                            type="text"
                            placeholder="Title"
                            name="title"
                            value="{{ old('title') }}"
                        >
                        @error('title')
                            <span class="text-xs text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="part_1"><b>First part</b></label>
                    <textarea name="part_1" id="part_1">{{ old('part_1') }}</textarea>
                    @error('part_1')
                        <span class="text-xs text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="col-md-4">
                    <label for="part_2"><b>Second part</b></label>
                    <textarea name="part_2" id="part_2">{{ old('part_2') }}</textarea>
                    @error('part_2')
                        <span class="text-xs text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="col-md-4">
                    <label for="part_3"><b>Third part</b></label>
                    <textarea name="part_3" id="part_3">{{ old('part_3') }}</textarea>
                    @error('part_3')
                        <span class="text-xs text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary mt-3">Add</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/lyrics/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid mt-5">
        <div>
            <div>
                <h1 class="mb-5">Edit Lyric</h1>
            </div>
        </div>
        <form
            method="post"
            action="{{ route('lyrics.update', $lyric->id) }}"
            class="container-fluid border-start border-primary p-3"
        >
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-12">
                    <div class="mb-3">
                        <label for="title"><b>Title</b></label>
                        <input
                            class="form-control"
                            id="title"
                            type="text"
                            placeholder="Title"
                            name="title"
                            value="{{ old('title', $lyric->title) }}"
                        >
                        @error('title')
                            <span class="text-xs text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="col-md-4">
                    <label for="part_1"><b>First part</b></label>
                    <textarea name="part_1" id="part_1">{{ old('part_1', $lyric->part_1) }}</textarea>
                    @error('part_1')
                        <span class="text-xs text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="col-md-4">
                    <label for="part_2"><b>Second part</b></label>
                    <textarea name="part_2" id="part_2">{{ old('part_2', $lyric->part_2) }}</textarea>
                    @error('part_2')
                        <span class="text-xs text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="col-md-4">
                    <label for="part_3"><b>Third part</b></label>
                    <textarea name="part_3" id="part_3">{{ old('part_3', $lyric->part_3) }}</textarea>
                    @error('part_3')
                        <span class="text-xs text-danger">{{ $message }}</span>
                    @enderror
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary mt-3">Update</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/lyrics/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid mt-5">
        <div>
            <div>
                <h1 class="mb-5">My Lyrics</h1>
                @include('layouts.notifications')
            </div>
        </div>
        <table class="table table-bordered bg-white">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Created</th>
                    <th scope="col">Last update</th>
                    <th scope="col">Actions</th>
                    <th scope="col">Export</th>
                </tr>
            </thead>
            <tbody>
                @forelse($lyrics as $key => $lyric)
                    <tr>
                        <td><b>{{ $key + 1 }}</b></td>
                        <td>{{ $lyric->title }}</td>
                        <td>{{ $lyric->created_at }}</td>
                        <td>{{ $lyric->updated_at }}</td>
                        <td>
                            <a href="{{ route('lyrics.show', $lyric->id) }}" target="_blank" class="btn btn-success btn-xs">
                                Preview
                            </a>
                            <a href="{{ route('lyrics.edit', $lyric->id) }}" class="btn btn-primary btn-xs">
                                Edit
                            </a>
                            <form action="{{ route('lyrics.destroy', $lyric->id) }}" class="d-inline-block" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-xs">
                                    Delete
                                </button>
                            </form>
                        </td>
                        <td>
                            <form action="{{ route('pdf.generate', $lyric->id) }}" method="post">
                                @csrf
                                <button type="submit" class="btn btn-yellow btn-xs">
                                    Generate PDF & export ZIP
                                </button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="12" class="text-center">
                            No lyrics found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
@endsection